name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setip-node@v4
        with:
          node-version: 20.x
      - run: bun install
      - run: bun lint
